name: 'PR Title Lint GitHub Action'
description: 'PR Title Lint for GitHub Actions'
author: 'Bonivan'
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  title-regex:
    description: 'Title regex to match'
    required: true
    default: '^\[PROJECT-\d*\]\ '
  error-message:
    description: 'Error message shown if title check fails'
    required: false
  exclude-files-regex:
    description: 'Do not run title check if all files changed in PR pass this regex'
    required: false
    default: ''